### ISSUE TITLE
部署完成后无法使用

### ISSUE THREAD

**Issue by Qiuyebai-1226** [Hideipnetwork/hideipnetwork-web#5]
部署了前后端，nginx设置了反代，能够打开前端页面，后台没有报错。
输入密码没有反应，修改配置文件的密码后可以输入密码进行验证，但输入网址无法跳转。
前端截图
![前端能够正常打开](https://user-images.githubusercontent.com/62199231/201307772-f2b901f3-fd40-4eb2-ab35-3fafabb41ef3.jpg)
后端api日志
![QQ截图20221111171747](https://user-images.githubusercontent.com/62199231/201307781-e1228fdb-d294-4336-bb31-9cc4ed3f37ee.jpg)
前端后台日志
![QQ截图20221111171808](https://user-images.githubusercontent.com/62199231/201307787-5cf0e611-2f6f-4ac9-bac9-c85223ed7f27.jpg)

**Comment by Qiuyebai-1226** [comment]
不改，改成http://127.0.0.1:3001,或者http://服务器ip:3001,都试过了 当然都是用base64编码过的。加了tls证书转成https也是一样的

**Comment by polojure** [comment]
同样出现了这种问题
web界面使用nginx反向代理
![image](https://user-images.githubusercontent.com/116640545/203715824-fe926983-e432-46c9-9889-1ebb396468fa.png)
admin api也部署完成
![image](https://user-images.githubusercontent.com/116640545/203716355-04181376-91c4-429f-946d-6f05f59dd822.png)
global已修改
出现可以输入密码进行验证，但输入网址无法跳转的问题
我打开过调试台看了一下，在我输入网址按下回车键时，网页并没有发出任何请求

**Comment by metmare** [comment]
请问解决了吗？我遇到了一样的问题，输入密码验证成功，但是后面搜索内容没有反应

**Comment by polojure** [comment]
控制台会打出这样的错误
![image](https://user-images.githubusercontent.com/116640545/203810920-03ac131f-f7e6-41b5-b80c-0256f510b757.png)

**Comment by polojure** [comment]
> 请问解决了吗？我遇到了一样的问题，输入密码验证成功，但是后面搜索内容没有反应

我的问题解决了，我给它加上了ssl证书，使用https协议，就没报错了

**Comment by superen7527** [comment]
兄弟你咋用的证书啊？我只会堡塔里面新建网站加证书，命令行嗯不晓得咋搞 能说一下嘛

**Comment by Qiuyebai-1226** [comment]
![QQ截图20230123163517](https://user-images.githubusercontent.com/62199231/213996419-f2a50b2a-c858-40fc-bcd2-2b362eb0cf58.png)
replit上有个类似的项目，fork一下就能运行了，不需要手动配置和服务器，速度还可以，如果只是想要个代理网页可以不用折腾了

**Comment by kaixin1995** [comment]
> 

哥们，能发一下这个的地址吗？

**Comment by kaixin1995** [comment]
> ![QQ截图20230123163517](https://user-images.githubusercontent.com/62199231/213996419-f2a50b2a-c858-40fc-bcd2-2b362eb0cf58.png) replit上有个类似的项目，fork一下就能运行了，不需要手动配置和服务器，速度还可以，如果只是想要个代理网页可以不用折腾了

哥们，能发一下这个的地址吗？

**Comment by kaixin1995** [comment]
@Qiuyebai-1226

**Comment by Qiuyebai-1226** [comment]
> > ![QQ截图20230123163517](https://user-images.githubusercontent.com/62199231/213996419-f2a50b2a-c858-40fc-bcd2-2b362eb0cf58.png) replit上有个类似的项目，fork一下就能运行了，不需要手动配置和服务器，速度还可以，如果只是想要个代理网页可以不用折腾了
> 
> 哥们，能发一下这个的地址吗？

原项目作者删掉了，这里是我的备份，改了点页面 https://replit.com/@qybyyds2023/Best-Proxy-Browser
